# Generated by Django 4.2.15 on 2024-08-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
